name: Fine Mountain Consulting
favicon: null
layout_spectrum: 0.9090313843917102
typography_spectrum: 0.9364678000565618
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6672018291428685
  lightness: 0.7032783871982247
  saturation: 0.27847259026020765
  rhythmicContrast: 0.7847693702206016
purpose: []
